version: "3.8"

services:
  vertex:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8989:8989"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - GOOGLE_CLOUD_PROJECT=citric-lead-450721-v2
    volumes:
      - ./credentials.json:/app/credentials.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
